### PR TITLE
Bootstrap4 test

### PR DESCRIPTION
**Pull request by sydoluciani**
Adding a key stroke to prevent intermittent test failure.

### CODE REVIEW

**Comment by sydoluciani** [comment]
@stevepiercy 

Those intermittent errors are timing issues, and in the case of chaining actions, I should check if another wait can be added in middle of actions, but for now added another send_key to home to make sure the cursor starts at the begining of the input. The thing is, Selenim put the cursor end of the input field instead of begining of the field like what happens interacting with real browser, so we have to send it to begining of the field before entering the input, otherwise the input get misplaced like:
- {'texts':['401-18-8661']}
?                - -   -
+ {'texts':['140-11-8866']}

Regarding the contributing document:
[This is pointing](
https://github.com/Pylons/deformdemo/blob/master/CONTRIBUTING.txt) to [This](https://github.com/Pylons/deform/blob/master/CONTRIBUTING.rst) and neither has new instruction for installing geckodriver.

I will delete this branch if this time it passed in all 3 retries.

**Comment by stevepiercy** [comment]
@sydoluciani Travis will exit on the first success, and will try up to three times before finally exiting.

I blackified the file and pushed. It should pass lint now. I'll merge when successful.

I'll clean up my contributing PR.

**Comment by sydoluciani** [comment]
@stevepiercy  I have finally installed Black and pre-commit :)    

You can re-run this test couple of times to make sure there is no intermittent errors/failures.

I just started working on coverage, not sure how long it takes to complete those.

**Comment by stevepiercy** [comment]
I restarted just the py36 build. If it passes, that will be 3/3 successes, and I can merge. Thank you!

**Comment by stevepiercy** [comment]
Success! Merging.

**Comment by sydoluciani** [comment]
@stevepiercy  Great. Thanks.

I have deleted my branch and the fork.   

I let you know about my progress on coverage testing against schema.py and renderer.py in couple of days.

**Pull request merged**
