### PR TITLE
Add elif clause to run tests against Selenium container running in gi…

### PR DESCRIPTION
**Pull request by sydoluciani**
Adding container to Github Action to be able to run tests against Selenium container.

### CODE REVIEW

**Comment by stevepiercy** [comment]
@sydoluciani I've done some work on both deform and deformdemo, both master and 2.0-branch, switching to GHA and to pytest as the test runner. You might need to rebase your branch and push.

**Comment by sydoluciani** [comment]
@stevepiercy , if you can please stop this test.

This pull request is only to experiment starting a container withing the VM.
There are couple of ways to start a container in Github Workflows.
One would be starting container within VM, like the way it is currently setup in Deform or Deformdemo local test. tests are running within the VM against Selenium container that is started within the VM. 
 
The only way I found that we can pass ports and other options to container when container is being started is using [services](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices) and here is an [example](https://github.community/t/best-way-to-run-selenium-tests-with-php-apache/131299/2).

**Comment by sydoluciani** [comment]
@stevepiercy Test finally failed, but it took a while.

**Comment by sydoluciani** [comment]
@stevepiercy I am going to close this pull request once the testing is done, since I am removing all tests but only one to make the run time shorter.

This is another [example](https://github.com/actions/example-services/issues/20) that shows two different way of running steps, first one runs steps within Selenium container, and the second shows the steps running in VM.
The second one is the way we setup in local testing, and the way togo with Github Actions.

If you have time have a look and let me know what is your thought.

Thanks

**Comment by stevepiercy** [comment]
@sydoluciani when the build enters Selenium tests, there is no feedback. If a job's Functional web test step stalls for more than 6 minutes (a typical amount of time waiting for the full test suite to run) then it should be stopped. There is usually some valuable information in the log.

I also discovered that GHA will run multiple jobs in a queue, where Travis pops the oldest off the stack. You can jam as many jobs as you like into the queue and they will run concurrently.

My offer to add you to the Deform contributors group to be able to cancel workflows still stands.

I'll review the options and provide feedback shortly.

**Comment by sydoluciani** [comment]
There is two problem with this pull request.
First of all, [Selenium container](https://github.com/Pylons/deformdemo/pull/104/commits/89b31413bc1967300281dfa7130547e797c38b55#diff-03609cb60b0c6e92fb771eb8787d6722b8c31ca4c03eabc788e147acd8c6fb43R34) is not being started, I am not seeing any log file stating it is started.

Sedond [GHA_CONTAINER_NAME](https://github.com/Pylons/deformdemo/pull/104/commits/bbb222ccbc46a00d7c5da92d11406e203ac38074#diff-03609cb60b0c6e92fb771eb8787d6722b8c31ca4c03eabc788e147acd8c6fb43R55) is not being exported from ci-tests.yml as expected, if it it is exported, then this [clause](https://github.com/Pylons/deformdemo/pull/104/commits/ecb93512abae91e5101cf7186b070a60588ad829#diff-e1608f44e2798812f15d2c4a50224a8eabd5e8604a8bffbf981523345ae6e130R330) condition would be true and starts tests against Selenium container.

**Comment by sydoluciani** [comment]
> There is two problem with this pull request.
> First of all, [Selenium container](https://github.com/Pylons/deformdemo/pull/104/commits/89b31413bc1967300281dfa7130547e797c38b55#diff-03609cb60b0c6e92fb771eb8787d6722b8c31ca4c03eabc788e147acd8c6fb43R34) is not being started, I am not seeing any log file stating it is started.
> 
> Sedond [GHA_CONTAINER_NAME](https://github.com/Pylons/deformdemo/pull/104/commits/bbb222ccbc46a00d7c5da92d11406e203ac38074#diff-03609cb60b0c6e92fb771eb8787d6722b8c31ca4c03eabc788e147acd8c6fb43R55) is not being exported from ci-tests.yml as expected, if it it is exported, then this [clause](https://github.com/Pylons/deformdemo/pull/104/commits/ecb93512abae91e5101cf7186b070a60588ad829#diff-e1608f44e2798812f15d2c4a50224a8eabd5e8604a8bffbf981523345ae6e130R330) condition would be true and starts tests against Selenium container.

@stevepiercy  Second problem seemed to be fixed, had to include GHA_CONTAINER_NAME to tox.ini.
now proper clause being selected, but still not seeing any Selenium container started in log files.
there are some errors related to network, and I am going to check why Selenium container not being started.

**Comment by sydoluciani** [comment]
@stevepiercy It is done, but now should find a fix for the fix 😄 
This is the problem I had in my local test and I had to place ip address of the VM in URL, otherwise network failure.
Should find a way to inject VM ip address in URL environment variable defined [here](https://github.com/Pylons/deformdemo/pull/104/commits/bf5ef3d6c64ad81d2ce2d458c5f142cc781e3742#diff-03609cb60b0c6e92fb771eb8787d6722b8c31ca4c03eabc788e147acd8c6fb43R61)

**Comment by sydoluciani** [comment]
@stevepiercy I have finally found a way to set the URL to include host ip address dynamically instead of hard coding the ip addrees. 

I am going to submit a fresh pull request tomorrow afternoon, dropping Xvfb and include Selenium container, and once it is merged going to close this one.

**Comment by stevepiercy** [comment]
@sydoluciani awesome! Thanks for your work on this. I'm looking forward to it.

**Comment by sydoluciani** [comment]
Complete changes are submitted through pull request #106 , closing this pull request.

**Comment by arkadiuszkrupa21** [comment]
> Adding container to Github Action to be able to run tests against Selenium container.

**Pull request closed without merging**
