### PR TITLE
[WIP] Add examples of using `tags` options on `Select2Widget` 

### PR DESCRIPTION
**Pull request by enkidulan**
**Original issue**: Pylons/deform#372
**Depends on**: https://github.com/Pylons/deform/pull/373.

**Tags multiple example**:
multytag

**Tags example**:
tag

### CODE REVIEW

**Comment by stevepiercy** [comment]
@enkidulan https://github.com/Pylons/deform/pull/373 has been merged, so this PR can be merged with a little help from you. Would you please rebase your PR on master and push?

I'm preparing a release of Deform 3.0, and I'd like this to be included in the demo. Thank you!

**Comment by enkidulan** [comment]
Nice, a shiny and new major release! I'll try to take a look today or tomorrow :)

**Comment by stevepiercy** [comment]
@enkidulan do you know how to run the tests locally with tox or nosetests? I just recently updated the [README.rst](https://github.com/Pylons/deformdemo) to be more complete, as well as [Deform's contributing.md](https://github.com/Pylons/deform/blob/master/contributing.md). Hope that helps.

**Comment by enkidulan** [comment]
@stevepiercy thanks, I'd managed to get linting and tests running on my PC, but I got somewhat different behavior than on Travis. The tricky parts for me were:
* for the lining part I needed to read `.travis.yaml` and install `lint` extras,
* tests were flaky on my PC, until once again I took a look at Travis and noticed `--with-flaky --max-runs=4` option, but
* I've been using the latest version of python libs, so were getting different errors locally. I think that I've run `install -e .[tests]` when I saw that flake8 and black are missing, so that's why `requirements-dev.txt` didn't take an effect, or maybe pipevn have upgraded the deps when I ran `install -e .[lint]`...

**Comment by stevepiercy** [comment]
Thanks @enkidulan! This PR is good. I've merged it.

For your setup:
1. What operating system are you running?
2. How did you install requirements?
3. How do you run tests? When I run `tox -e lint`, tox installs the requirements in its own virtual environment at `.tox/lint/lib/python3.6/site-packages/` and runs all the lint checks.
4. `pip install -e .[tests]` should do nothing. `pip install -e .["testing"]` should install only the testing dependencies, but not deform or colander. `$VENV/bin/pip install -Ur requirements-dev.txt` should install everything needed to run tests and do development.

I found a mistake in the README.rst under Selenium install, and corrected that to be consistent with install testing and dev reqs.

**Comment by enkidulan** [comment]
Cool, thanks!

As for your questions:
1. Fedora 32
2. I didn't follow the README and used `pipevn` instead of `pip`
3. Just `nosetests`
4. sorry, I've meant `testing`, not `tests`, typo on my part.

I hope that helps.

**Comment by stevepiercy** [comment]
2. I'm not familiar with `pipenv` usage when developing, but I assume that if you used `-e`—whether via `pip` or `pipenv`—then you would have no problem. There might be some obscure difference, and, if so, it would be good to document it.

3. Yeah, `nosetests` does not install dependencies for linting. Also when you install `requirements-dev.txt`, it will install Deform from GitHub and not link to your local Deform src. That means you were running tests against Deform 2.0.8, and not anything that you updated. This is not obvious. Instead I followed https://github.com/Pylons/deform/blob/master/contributing.md as it allows me to test my changes in Deform in deformdemo.

**Pull request merged**
