### PR TITLE
Fixed test failures on input fields.

### PR DESCRIPTION
**Pull request by sydoluciani**
Pushing the change to deformdemo to be able to test deform functional tests.

### CODE REVIEW

**Comment by stevepiercy** [comment]
Let's get this build to pass.

Drop these lines:
- https://github.com/Pylons/deformdemo/blob/master/.travis.yml#L3  # deprecated
- https://github.com/Pylons/deformdemo/blob/master/.travis.yml#L10-L11  # Python 2
- https://github.com/Pylons/deformdemo/blob/master/.travis.yml#L25-L26  # obsolete per https://benlimmer.com/2019/01/14/travis-ci-xvfb/

Add after `addons`:
```yaml
services:
  - xvfb
```

**Comment by stevepiercy** [comment]
These tests look good. If the build does not pass, I will try them out in my dev to see what's going on.

**Comment by stevepiercy** [comment]
Lint now passes, and xvfb now starts. All but one test pass, for [deformdemo.test.CheckedInputWidgetWithMaskTests::test_type_bad_input](https://travis-ci.org/github/Pylons/deformdemo/jobs/685189550#L307).

**Comment by sydoluciani** [comment]
We have to change "findid(id)" to action_chains_on_id(id).click().restoffindid.perform()
 on method that is failing.

 I am going to make the change and push it shortly.

**Comment by sydoluciani** [comment]
All failures are fixed.  
I am going to start working on Errors tomorrow.  

Why lint is failing ?

**Comment by stevepiercy** [comment]
We use [Black](https://github.com/psf/black) when linting. You can also use it with [pre-commit](https://pre-commit.com/). These are tools that the core Pylons Project team members use to avoid formatting issues and to do it automatically as a hook before making a commit.

**Comment by stevepiercy** [comment]
I pushed up a Black-ified commit. Lint passes now.

**Comment by sydoluciani** [comment]
@stevepiercy  Errors are fixed and functional tests are being passed with no error on my local server, however it is failing in Travis environment.

It might be related to version of Selenium in Travis:
AttributeError: module 'selenium.webdriver.support.expected_conditions' has no attribute 'url_contains'

[Here is the reference](https://www.selenium.dev/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.expected_conditions.html#selenium.webdriver.support.expected_conditions.url_contains)

**Comment by sydoluciani** [comment]
On top of the report says: "selenium==2.53".     
once selenium upgrades, it should pass all tests.   

Is Lint going to fail just becuase I don't have Black installed ?   

I work on coverage report tomorrow.

**Comment by sydoluciani** [comment]
OK, my bad, I had to updated requirements-dev.txt and setup.py and change "selenium<3" to "selenium>3".  awaiting for the result ......

**Comment by sydoluciani** [comment]
@stevepiercy Firefox needs to be upgraded in here as well, after upgrading Selenium, now Selenium looking for geckodriver:

https://travis-ci.org/github/Pylons/deformdemo/jobs/685441036#L425

**Comment by stevepiercy** [comment]
@sydoluciani lint will fail unless you install and use Black, unless you happen to follow Black's requirements manually.

I will work on the gecko/firefox issue, if you haven't done so already.

**Comment by sydoluciani** [comment]
@stevepiercy I assumed Firfox and geckodriver upgrade needs administrative access on Travis !!! could I do the upgrade just as a normal user ? 

I noticed you metioned if I want to work on Selenium-Firefox Docker the other time, but I didn't bring it up, since that was a pretty long way to go.

**Comment by stevepiercy** [comment]
@sydoluciani yes, you can try out specs for anything in Travis. Just make changes to `.travis` in your PR.

I'm experimenting on [my branch](https://github.com/Pylons/deform/pull/400) and you can see what I tried and failed so far to save yourself some trial and error. Right now I'm struggling with getting Travis to find the Firefox binary. This Travis doc might be helpful: https://docs.travis-ci.com/user/gui-and-headless-browsers/

The [Travis docs are silent about how to install geckodriver](https://github.com/travis-ci/docs-travis-ci-com/search?q=geckodriver&unscoped_q=geckodriver&type=Issues).

I suck at Docker. I won't be much help for that.

**Comment by stevepiercy** [comment]
Hey @sydoluciani it looks like I got it running finally! https://travis-ci.org/github/Pylons/deform/builds/685462054

**Comment by stevepiercy** [comment]
Now that it is running, although failing tests that you fixed in the other PRs, one of us can merge the diff to your branch in https://github.com/Pylons/deform/pull/397. I can do it in about 4 hours, if you don't have the time. My branch is a mess of commits and I'm fine with closing it in favor of yours.

**Comment by sydoluciani** [comment]
@stevepiercy Thanks for the info, so only .travis.yml needs to be updated to upgrade firefox, Selenium , etc ..., I am going to upgrade Firefox in this branch of deformdemo.

If we delete "deformdemo_functional_tests" in local Deform folder, then fresh deformdemo will be downloaded in Deform, that includes all of our new changes in deformdemo, but not sure how that works in travis. I will check Deform when Deformdemo is completed.

https://github.com/sydoluciani/deform/blob/master/run-selenium-tests.bash#L14

Lets complete Deformdemo first, then I am going to work on coverage tests on your branch, to commit your branch. once done, then you can create a new branch and just copy the bootstrap 4 js and css, all these changes was overdue and not related to upgrade.

**Comment by sydoluciani** [comment]
@stevepiercy  it passed all the tests.

**Comment by stevepiercy** [comment]
This looks great. Thank you!

I want to clean up a few things between requirements-dev.txt and setup.py, so I'll push some commits in a couple minutes.

**Comment by stevepiercy** [comment]
Interesting. On the first of three runs, [this test failed](https://travis-ci.org/github/Pylons/deformdemo/jobs/685518253#L332). On the second run, it passed. `¯\_(ツ)_/¯`

Anyway, this is good to go. I'll merge this.

Eventually I want to cut a release for both deform and deformdemo v.3.0.0, but that will come after your work in deform.

**Pull request merged**
